### ISSUE TITLE
feature request: Add taplo formatter support for TOML

### ISSUE THREAD

**Issue by snowman** [lassik/emacs-format-all-the-code#194]
see https://taplo.tamasfe.dev/cli/usage/formatting.html for more information

**Comment by lassik** [comment]
Please check whether PR #196 makes taplo work for you. If it works, I'll merge it.

**Comment by snowman** [comment]
I had tried the example from https://toml.io/en/

```toml
# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"
```

`M-x format-all-buffer RET` works either for buffer with/without
associated filename. It works 👍
